### Criar
POST http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZjU1MzM1Yi02YjdkLTRmMTEtYWIyYi01NTgyYzM5ZjRhZDQiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc2MDY0NjgxMX0.ay9yC8667Lw6N7xmgGKPG0D2ed2fdUqTT5SLBSdl4CM

{
  "title": "Curso de Java"
}

### Buscar
GET http://localhost:3333/courses?orderBy=title

### Buscar por ID
GET http://localhost:3333/courses/592449cf-2bfa-4994-84ab-4e832d8dac72
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZjU1MzM1Yi02YjdkLTRmMTEtYWIyYi01NTgyYzM5ZjRhZDQiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc2MDYzNzA4MX0.h7zyehBxaHAFCERbuqehKukhqEvzGsVXz0jPCKxXArw

### Login
POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "Marcelo24@bol.com.br",
  "password": "123456"
}